### ISSUE TITLE
transfer over ownership

### ISSUE THREAD

**Issue by flokli** [tweag/gerrit-queue#8]
I'd like to keep maintaining this project, but I'm not part of tweag anymore.

Forking would be an option, but by transferring the repo, issues would get moved and people would get redirected, which provides a nicer UX.

Can we transfer this repo to `flokli/gerrit-queue`?

cc @mboes

**Comment by aspiwack** [comment]
Hi Florian,

Nice to hear from you :slightly_smiling_face: .

Indeed there is no momentum here to maintain the project, I'll gladly transfer it to you.

**Comment by aspiwack** [comment]
Github tells me that you already have a fork. You will have to delete it (or rename it, presumably?) for me to transfer the main repository to you. I'll transfer as soon as possible once you do.

**Comment by flokli** [comment]
Thanks for replying back!

The fork should now be out of the way. Let me know if the transfer works :-)

**Comment by aspiwack** [comment]
Damn… Github now complains that you have a fork. The documentation indeed states:
> The target account must not have a repository with the same name, or a fork in the same network.

This is a bit tiresome. I don't know what the best option is from your end. But it does appear that merely renaming wasn't enough :slightly_frowning_face: . Back to you again…

**Comment by flokli** [comment]
:facepalm: Okay, now it should be gone for sure. Passing the ball to you :laughing:

**Comment by aspiwack** [comment]
Alright. I've had to indirect through myself (because you can only transfer out of an organisation to your own account). You should now have received a request email to accept the transfer, if I understand correctly.

Once this is done, you can remove me from the collaborator list (in which I will be automatically added), and close this issue :slightly_smiling_face:

**Comment by flokli** [comment]
Done. Thanks!
